name = "kimpure/supportjs"
version = "0.1.0"
authors = ["kimpure"]
repository = "https://github.com/kimpure/supportJs.luau"
license = "MIT"
includes = [ "src/**", "pesde.toml", "licence", "readme.md" ]

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
